# Generated by Django 4.2.5 on 2023-11-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_batch_remove_sku_id_alter_sku_sku_order_line_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_line_item',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
