# Generated by Django 4.2.5 on 2023-11-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_variation_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_line_item',
            name='item_site_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
