# Generated by Django 4.2.5 on 2023-11-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_order_line_item_item_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='attributes_id',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
