# Generated by Django 4.2.5 on 2023-11-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_shipping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
