# Generated by Django 4.2.5 on 2023-11-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='email',
        ),
    ]
