# Generated by Django 4.2.5 on 2023-11-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_shipping_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='tracking_number',
            field=models.JSONField(null=True),
        ),
    ]
