# Generated by Django 4.2.5 on 2023-11-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_shipping_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='webhook_id',
            field=models.JSONField(null=True),
        ),
    ]
