# Generated by Django 4.2.5 on 2023-11-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_site_webhook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
