# Generated by Django 4.2.5 on 2023-11-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_product_site_product_site_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Site',
        ),
    ]
