# Generated by Django 4.2.5 on 2023-11-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_delete_product_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Site',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_site_id', models.CharField(max_length=255)),
                ('product_site_name', models.CharField(max_length=255, null=True)),
                ('link', models.URLField(unique=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('date_modified', models.DateTimeField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.site')),
            ],
        ),
    ]
