# Generated by Django 4.2.5 on 2023-11-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_product_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Site',
        ),
    ]
