# Generated by Django 4.2.5 on 2023-11-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_product_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_site',
            name='id',
        ),
        migrations.AlterField(
            model_name='product_site',
            name='link',
            field=models.URLField(primary_key=True, serialize=False, unique=True),
        ),
    ]
