# Generated by Django 4.2.5 on 2023-11-14 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_rename_product_id_variation_product_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='product_site',
            new_name='product_site_id',
        ),
    ]
