# Generated by Django 4.2.5 on 2023-11-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_rename_product_site_variation_product_site_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='webhook_id',
        ),
    ]
