# Generated by Django 4.2.5 on 2023-11-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_variation_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='order_line_item',
            name='sku',
        ),
        migrations.DeleteModel(
            name='SKU',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
