# Generated by Django 4.2.5 on 2023-11-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=255)),
                ('attributes', models.JSONField()),
                ('quantity', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('child_sku', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
