# Generated by Django 4.2.5 on 2023-11-16 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='sku',
            new_name='sku_id',
        ),
    ]
