# Generated by Django 4.2.5 on 2023-11-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_remove_variation_sku_id_order_line_item_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='sku',
        ),
    ]
