# Generated by Django 4.2.5 on 2023-11-16 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_remove_variation_site_id_remove_variation_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=255)),
                ('attributes', models.JSONField()),
                ('quantity', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('child_sku', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_site_id', models.CharField(max_length=255)),
                ('product_site_name', models.CharField(max_length=255, null=True)),
                ('attributes_id', models.CharField(default='NA', max_length=500)),
                ('attributes', models.JSONField()),
                ('date_modified', models.DateTimeField()),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.site', verbose_name='site')),
                ('sku', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.sku')),
            ],
        ),
        migrations.AddField(
            model_name='order_line_item',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sku'),
        ),
    ]
