# Generated by Django 4.2.5 on 2023-11-16 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_sku_variation_order_line_item_sku'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('site_id', 'product_site_id', 'attributes_id')},
        ),
    ]
