# Generated by Django 4.2.5 on 2023-11-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_alter_sku_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
