# Generated by Django 4.2.5 on 2023-11-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_alter_sku_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='attributes_id',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='variation',
            name='attributes_id',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
