# Generated by Django 4.2.5 on 2023-11-16 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_alter_sku_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.site'),
        ),
    ]
