# Generated by Django 4.2.5 on 2023-11-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_alter_variation_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_items',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order_line_item',
            name='date_created',
            field=models.DateTimeField(default='2023-11-17'),
        ),
    ]
