# Generated by Django 4.2.5 on 2023-11-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_order_line_item_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number_items',
        ),
    ]
