# Generated by Django 4.2.5 on 2023-11-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_remove_order_number_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_items',
            field=models.IntegerField(default=1),
        ),
    ]
