# Generated by Django 4.2.5 on 2023-11-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_order_number_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_line_item',
            name='date_created',
        ),
    ]
