# Generated by Django 4.2.5 on 2023-11-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_alter_order_line_item_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('Processing', 'PROCESSING'), ('Completed', 'COMPLETED'), ('Canceled', 'CANCELED')], default='Processing', max_length=50),
        ),
        migrations.AddField(
            model_name='order_line_item',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('On-Hold', 'ON-HOLD'), ('Failed', 'FAILED'), ('Processing', 'PROCESSING'), ('Fulfilling', 'FULFILLING'), ('Cancelled', 'CANCELLED'), ('Completed', 'COMPLETED'), ('Refunded', 'REFUNDED')], default='Pending', max_length=50),
        ),
    ]
