# Generated by Django 4.2.5 on 2023-11-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_remove_order_line_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_line_item',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('On-Hold', 'ON-HOLD'), ('Failed', 'FAILED'), ('Processing', 'PROCESSING'), ('Fulfilling', 'FULFILLING'), ('Cancelled', 'CANCELLED'), ('Completed', 'COMPLETED'), ('Refunded', 'REFUNDED')], default='Pending', max_length=50),
        ),
    ]
