# Generated by Django 4.2.5 on 2023-11-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_order_line_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfill_status',
            field=models.FloatField(default=0),
        ),
    ]
