# Generated by Django 4.2.5 on 2023-11-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_order_fulfill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_line_item',
            name='item_site_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
