# Generated by Django 4.2.5 on 2023-11-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_rename_item_site_id_order_line_item_line_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='product_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
