# Generated by Django 4.2.5 on 2023-11-21 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_alter_sku_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_site',
            old_name='site',
            new_name='site_id',
        ),
    ]
