# Generated by Django 4.2.5 on 2023-11-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_rename_site_product_site_site_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_site',
            name='product',
        ),
        migrations.AddField(
            model_name='product_site',
            name='product_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
