# Generated by Django 4.2.5 on 2023-11-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_remove_product_site_product_product_site_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_line_item',
            name='sku',
        ),
        migrations.AlterField(
            model_name='variation',
            name='sku',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='SKU',
        ),
    ]
