# Generated by Django 4.2.5 on 2023-11-22 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_order_line_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_line_item',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sku', to_field='sku'),
        ),
    ]
