# Generated by Django 4.2.5 on 2023-11-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_alter_order_line_item_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
