# Generated by Django 4.2.5 on 2023-11-22 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.site', to_field='link', verbose_name='site'),
        ),
    ]
