# Generated by Django 4.2.5 on 2023-11-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_remove_order_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='site_id',
            field=models.ForeignKey(default='SEM', on_delete=django.db.models.deletion.CASCADE, to='dashboard.site', verbose_name='site'),
        ),
    ]
