# Generated by Django 4.2.5 on 2023-11-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_order_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_line_item',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
