# Generated by Django 4.2.5 on 2023-11-23 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_alter_order_line_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_line_item',
            name='sku',
        ),
        migrations.DeleteModel(
            name='SKU',
        ),
    ]
