# Generated by Django 4.2.5 on 2023-11-23 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_remove_sku__id_alter_order_line_item_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('sku', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=255, null=True)),
                ('attributes_id', models.CharField(max_length=255)),
                ('attributes', models.JSONField()),
                ('quantity', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('child_sku', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order_line_item',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sku'),
        ),
    ]
