# Generated by Django 4.2.5 on 2023-11-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_remove_shipping_address_1_remove_shipping_address_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order_line_item',
            name='fulfill_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_line_item',
            name='tag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfill_status',
            field=models.IntegerField(default=0),
        ),
    ]
