# Generated by Django 4.2.5 on 2023-11-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_shipping_shipping_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='line_item_id',
        ),
        migrations.AddField(
            model_name='shipping',
            name='line_item_id',
            field=models.ManyToManyField(to='dashboard.order_line_item'),
        ),
    ]
