# Generated by Django 4.2.5 on 2023-11-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_remove_shipping_line_item_id_shipping_line_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
