# Generated by Django 4.2.5 on 2023-11-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_alter_batch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='valid_amount_fulfillment',
            field=models.FloatField(default=0),
        ),
    ]
