# Generated by Django 4.2.5 on 2023-11-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_rename_valid_amount_fulfillment_order_number_items_fulfilled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_line_item',
            name='status',
        ),
    ]
