# Generated by Django 4.2.5 on 2023-11-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_remove_order_line_item_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_line_item',
            old_name='fulfill_status',
            new_name='status',
        ),
    ]
