# Generated by Django 4.2.5 on 2023-11-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_alter_order_line_item_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_detail',
            name='tracking_detail',
            field=models.TextField(null=True),
        ),
    ]
