# Generated by Django 4.2.5 on 2023-11-29 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_order_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_detail',
            name='tracking_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_details', to='dashboard.shipping'),
        ),
    ]
