# Generated by Django 4.2.5 on 2023-12-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_alter_shipping_line_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='delivery_status',
            field=models.IntegerField(default=0),
        ),
    ]
