# Generated by Django 4.2.5 on 2023-12-06 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_variation_variation_id_alter_shipping_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=255)),
                ('coupon_site_id', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('minimum_amount', models.FloatField(default=0)),
                ('maximum_amount', models.FloatField(default=0)),
                ('description', models.TextField(null=True)),
                ('discount_type', models.CharField(max_length=255, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('usage_limit', models.IntegerField(default=0)),
                ('usage_limit_per_user', models.IntegerField(default=0)),
                ('date_expires', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.site')),
            ],
            options={
                'unique_together': {('site_id', 'coupon_site_id')},
            },
        ),
    ]
