# Generated by Django 4.2.5 on 2023-12-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0099_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='usage_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit_per_user',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
