# Generated by Django 4.2.5 on 2023-12-06 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0100_alter_coupon_usage_count_alter_coupon_usage_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('enabled', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('method_title', models.CharField(max_length=255)),
                ('method_description', models.TextField(null=True)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.site')),
            ],
            options={
                'unique_together': {('site_id', 'payment_gateway_id')},
            },
        ),
    ]
