# Generated by Django 4.2.5 on 2023-12-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0102_shipping_current_number_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='current_number_details',
        ),
    ]
