# Generated by Django 4.2.5 on 2023-12-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0103_remove_shipping_current_number_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_detail',
            name='detail_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='shipping_detail',
            unique_together={('tracking_number', 'detail_index')},
        ),
    ]
