# Generated by Django 4.2.5 on 2023-12-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_useractionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
