# Generated by Django 4.2.5 on 2023-12-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0107_order_dashboard_o_date_cr_7f8bc7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_line_item',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
