# Generated by Django 4.2.5 on 2023-12-08 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0109_remove_order_number_items_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_line_item',
            name='batch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='dashboard.batch'),
        ),
    ]
