# Generated by Django 4.2.5 on 2023-12-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_alter_order_line_item_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
