# Generated by Django 4.2.5 on 2023-12-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0111_alter_batch_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
