# Generated by Django 4.2.5 on 2023-12-13 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0112_alter_batch_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
