# Generated by Django 4.2.5 on 2023-12-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0114_remove_order_fulfill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='object_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='object_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
