# Generated by Django 4.2.5 on 2023-12-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0115_useractionlog_object_id_useractionlog_object_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date_paid'], name='dashboard_o_date_pa_47f399_idx'),
        ),
    ]
