# Generated by Django 4.2.5 on 2023-12-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0116_order_dashboard_o_date_pa_47f399_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='meta_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='attributes',
            field=models.JSONField(null=True),
        ),
    ]
