# Generated by Django 4.2.5 on 2023-12-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0117_variation_meta_data_alter_variation_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='attributes',
            field=models.JSONField(null=True),
        ),
    ]
