# Generated by Django 4.2.5 on 2023-12-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0118_alter_sku_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_line_item',
            name='meta_data_id',
            field=models.JSONField(null=True),
        ),
    ]
