# Generated by Django 4.2.5 on 2023-12-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0120_remove_variation_variation_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment_gateway',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='payment_gateway',
            name='site_id',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Payment_Gateway',
        ),
    ]
