# Generated by Django 4.2.5 on 2023-12-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0121_alter_payment_gateway_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sku',
            unique_together={('product_id', 'attributes_id')},
        ),
    ]
