# Generated by Django 4.2.5 on 2023-12-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0122_alter_sku_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sku',
            unique_together=set(),
        ),
    ]
