# Generated by Django 4.2.5 on 2024-01-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0123_alter_sku_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template_Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template', models.JSONField(null=True)),
            ],
        ),
    ]
