# Generated by Django 4.2.5 on 2024-01-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0124_template_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_export',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
