# Generated by Django 4.2.5 on 2024-01-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0126_remove_order_line_item_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(unique=True)),
                ('type_api', models.CharField(max_length=255)),
                ('authentication', models.JSONField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
