# Generated by Django 4.2.5 on 2024-01-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0127_key_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_dispute',
            field=models.IntegerField(default=0),
        ),
    ]
