# Generated by Django 4.2.5 on 2024-01-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0128_order_is_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='key_api',
            name='code',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='key_api',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
