# Generated by Django 4.2.5 on 2024-01-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0129_key_api_code_alter_key_api_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispute_resolved',
            field=models.IntegerField(null=True),
        ),
    ]
