# Generated by Django 4.2.5 on 2024-01-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0132_variation_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product_id',
        ),
    ]
