# Generated by Django 4.2.5 on 2024-01-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0133_remove_variation_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_site',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
