# Generated by Django 4.2.5 on 2024-01-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0134_alter_product_site_date_modified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Site',
        ),
    ]
