# Generated by Django 4.2.5 on 2024-01-18 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0137_alter_variation_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_line_item',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sku'),
        ),
        migrations.AlterField(
            model_name='site',
            name='platform',
            field=models.CharField(default='WooCommerce', max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
