# Generated by Django 4.2.5 on 2024-01-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0139_product_site_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_sendmail',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='send_mail_status',
            field=models.IntegerField(default=0),
        ),
    ]
