# Generated by Django 4.2.5 on 2024-01-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0140_order_last_sendmail_order_send_mail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='last_sendmail',
            new_name='last_send_mail',
        ),
    ]
