# Generated by Django 4.2.5 on 2024-01-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0141_rename_last_sendmail_order_last_send_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_line_item',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
