# Generated by Django 4.2.5 on 2024-01-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0142_order_line_item_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_send_mail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='send_mail_status',
        ),
    ]
