# Generated by Django 4.2.5 on 2024-01-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0143_remove_order_last_send_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
