# Generated by Django 4.2.5 on 2024-01-25 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0144_email_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('Processed', models.JSONField(null=True)),
                ('Dropped', models.JSONField(null=True)),
                ('Delivered', models.JSONField(null=True)),
                ('Deferred', models.JSONField(null=True)),
                ('Bounce', models.JSONField(null=True)),
                ('Blocked', models.JSONField(null=True)),
                ('Open', models.JSONField(null=True)),
                ('Click', models.JSONField(null=True)),
                ('email_emplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='dashboard.email_template', to_field='name')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='dashboard.order')),
            ],
        ),
    ]
