# Generated by Django 4.2.5 on 2024-01-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0146_rename_blocked_email_sent_blocked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_sent',
            name='blocked',
        ),
    ]
