# Generated by Django 4.2.5 on 2024-01-25 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0147_remove_email_sent_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_sent',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
