# Generated by Django 4.2.5 on 2024-01-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0148_email_sent_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_template',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
