# Generated by Django 4.2.5 on 2024-01-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0149_email_template_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='auto_send_mail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
