# Generated by Django 4.2.5 on 2024-02-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0151_order_line_item_last_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_line_item',
            name='last_email',
        ),
        migrations.AddField(
            model_name='email_sent',
            name='line_item',
            field=models.JSONField(null=True),
        ),
    ]
