# Generated by Django 4.2.5 on 2024-03-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0154_order_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
    ]
