# Generated by Django 4.2.5 on 2024-03-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0156_sku_is_oldsku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number_items',
        ),
    ]
