# Generated by Django 4.2.5 on 2024-03-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0157_remove_order_number_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key_api',
            name='status',
        ),
        migrations.RemoveField(
            model_name='key_api',
            name='type_api',
        ),
    ]
