# Generated by Django 4.2.5 on 2024-04-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0159_uploaded_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_Email_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('condition', models.JSONField()),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
