# Generated by Django 4.2.5 on 2024-04-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0160_auto_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_email_template',
            name='content',
            field=models.TextField(),
        ),
    ]
