# Generated by Django 4.2.5 on 2024-04-19 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0161_alter_auto_email_template_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_sent',
            name='automail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='dashboard.auto_email_template', to_field='name'),
        ),
    ]
