# Generated by Django 4.2.5 on 2024-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0163_alter_order_address_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_2',
            field=models.TextField(null=True),
        ),
    ]
